spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DirZzz/Spring-Cloud.git
          search-paths: cloud-repo
server:
  port: 9200
