spring:
  application:
    name: cloud-server
  cloud:
    config:
      server:
        git:
          uri:https://github.com/DirZzz/Spring-Cloud.git
          username:
          password:
          search-paths: config-repo
server:
  port: 9200
